### ISSUE TITLE
Installation doesn't work: Unable to create resource URLImageDescriptor

### ISSUE THREAD

**Issue by igornem1** [eclipse-packaging/packages#187] opened 2024-06-25 11:07 UTC
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

Version: 2024-06 (4.32.0)
Build id: 20240606-1231

## Steps to reproduce

From a fresh installation and clean workspace:

* *Download package https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-06/R/eclipse-java-2024-06-R-linux-gtk-x86_64.tar.gz*
* *Unzip it*
* *Run /eclipse*

OR

* *Download Eclipse installer https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2024-06/R/eclipse-inst-jre-linux64.tar.gz*
* *Unzip it*
* *Run /eclipse-inst*
* *Selected [Eclipse IDE for Enterprise Java and Web Developers]*
* *Run installation*
* *Run /eclipse*

I tried

* *Run /eclipse*

I expected: *Regular Eclipse window*

But got: *Eclipse window with many errors(see screenshot)*
![eclipse](https://github.com/eclipse-platform/.github/assets/12052605/c8ef5db8-2585-4634-9c38-8038eec1509d)

## Here is attached log exported from Eclipse Workspace log tab

[eclipse.log](https://github.com/user-attachments/files/15969981/eclipse.log)

## Tested under this environment:

* OS & version:  Linux Mint 21.3
* Eclipse IDE/Platform version (as shown in *Help > About*): 
* Version: 2024-06 (4.32.0)
Build id: 20240606-1231

## Community

- [X] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by jonahgraham** [comment] 2024-06-25 12:46
This works for me on Linux too - the specific image that is raising an error is displayed as expected:

**Comment by jonahgraham** [comment] 2024-06-25 12:49
![image](https://github.com/eclipse-packaging/packages/assets/679236/dd164a2c-103c-428e-bca4-4f89131c30f7)

I am on Xubuntu 22.04, so a bit older linux. My guess is there is a problem related to the newer Linux version (Mint 21.3 release date is early 2024).

> Download package https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-06/R/eclipse-java-2024-06-R-linux-gtk-x86_64.tar.gz

The screenshots and error log are from JEE, but this step in your instructions says download Java version. Does the Java version (eclipse-java-2024-06-R) suffer from the same problem (but presumably different icons in error message)?

**Comment by jonahgraham** [comment] 2024-06-25 12:53
PS. As a workaround until we resolve this issue (assuming it is only affecting the Project Explorer badly). Close the Project Explorer, create a new project and then when you reopen the project explorer it shouldn't need to create those icons.

**Comment by igornem1** [comment] 2024-06-25 14:01
> The screenshots and error log are from JEE, but this step in your instructions says download Java version. Does the Java version (eclipse-java-2024-06-R) suffer from the same problem (but presumably different icons in error message)?

Oh, my bad, sorry, just mistacked with a link, actually was downloaded JEE version, just typo when filled the issue page, don't know if pure Java version has same problem.

ps. As workaround currently installed previous version and updated from it. 
Yet image errors on initial Java EE perspective(see screenshot), but noticed other similar error-popups when imported Maven project. Probably some other's views images missed too.
![image](https://github.com/eclipse-packaging/packages/assets/12052605/f551c95c-22b4-4e9a-9324-8608180bf5f9)

**Comment by Phillipus** [comment] 2024-06-25 16:49
I have  Linux Mint 21.3 (Cinnamon) installed in a VM.

I downloaded and installed the package from https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-06/R/eclipse-java-2024-06-R-linux-gtk-x86_64.tar.gz and the images are OK.

Looking at the error log all the images that couldn't be loaded are `.gif` format. We had a user of our RCP app report that some Linux distros have disabled support for some image formats. See https://github.com/archimatetool/archi/issues/1036#issuecomment-2118878984 and https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/commit/e052a112075a19fb75f1f2ff3de4c82923de13f2

But that shouldn't be the case for  Linux Mint 21.3. I use the Cinnamon version, maybe the Xfce or MATE versions are different?

**Comment by jonahgraham** [comment] 2024-06-25 18:31
Thanks @Phillipus for the insight. The changes in gdk-pixbuf are pretty recent and I can imagine we are about to start seeing the rollout of that change to early adopters of new versions. There was some discussion of reverting the change (https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/169) but that doesn't seem to have happened.

Quoting from that last link:

> The fix for most applications is trivial: just convert whatever icons are affected to png.

A quick count shows almost 1000 gifs in the various platform/jdt/pde/equinox projects and an impressive 32k across all projects in SimRel.

@akurtakov have you heard of this potential problem?

**Comment by Phillipus** [comment] 2024-06-25 18:52
> There was some discussion of reverting the change (https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/169) but that doesn't seem to have happened.

I'm not sure if this a revert? https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/846

**Comment by akurtakov** [comment] 2024-06-25 19:06
First time I hear of anything like this.

**Comment by igornem1** [comment] 2024-06-25 19:29
> @igornem1 Are you using the MATE version?

Nop, the Cinnamon version

**Comment by Phillipus** [comment] 2024-06-25 19:30
> Nop, the Cinnamon version

So am I but `gif` images are showing OK.

**Comment by igornem1** [comment] 2024-06-25 19:35
> > Nop, the Cinnamon version
> 
> So am I but `gif` images are showing OK.

Bingo!
![image](https://github.com/eclipse-packaging/packages/assets/12052605/d089e64c-cccb-4895-a12f-074fc8987e1c)

**Comment by Phillipus** [comment] 2024-06-25 19:37
So why are gifs OK on my version of Linux Mint?

**Comment by igornem1** [comment] 2024-06-25 19:38
> So why are gifs OK on my version of Linux Mint?

I would be happy to know it

**Comment by nitind** [comment] 2024-06-25 19:39
Are you able to query what version of the gdk library is installed?

**Comment by igornem1** [comment] 2024-06-25 19:42
And another case, for example in the log was errors similar to:
!MESSAGE The image could not be loaded: URLImageDescriptor(platform:/plugin/org.eclipse.jst.servlet.ui/icons/full/ctool16/newservlet_wiz.gif)

So I've paid attention that in archive either installed by installer the folder doesn't contain folder "plugin", but "plugins", but anyway the file "newservlet_wiz.gif" doesn't exists at all

**Comment by igornem1** [comment] 2024-06-25 19:43
> Are you able to query what version of the gdk library is installed?

Have know idea how to check it but if you'll teach me I can do it

**Comment by Phillipus** [comment] 2024-06-25 19:46
> So I've paid attention that in archive either installed by installer the folder doesn't contain folder "plugin", but "plugins", but anyway the file "newservlet_wiz.gif" doesn't exists at all

"plugin" is not a folder, it's a protocol. The image exists inside the plugin bundle.

**Comment by igornem1** [comment] 2024-06-25 19:52
> what version of the gdk library is installed
HTH:
$ dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'
ii  libgtk-3-0:amd64             3.24.33-1ubuntu2.1 amd64        GTK graphical user interface library
ii  libgtk-3-bin                 3.24.33-1ubuntu2.1 amd64        programs for the GTK graphical user interface library
ii  libgtk-3-common              3.24.33-1ubuntu2.1 all          common files for the GTK graphical user interface library
ii  libgtk2.0-0:amd64            2.24.33-2ubuntu2   amd64        GTK graphical user interface library - old version
ii  libgtk2.0-bin                2.24.33-2ubuntu2   amd64        programs for the GTK graphical user interface library
ii  libgtk2.0-common             2.24.33-2ubuntu2   all          common files for the GTK graphical user interface library
ii  libgtk3-perl                 0.038-1            all          Perl bindings for the GTK+ graphical user interface library

**Comment by igornem1** [comment] 2024-06-25 19:53
and
$ dpkg -l gtk* | grep -e '^i' | grep -e 'gtk-*[0-9]'
ii  gtk2-engines:amd64         1:2.20.2-5build2   amd64        theme engines for GTK+ 2.x
ii  gtk2-engines-murrine:amd64 0.98.2-3build2     amd64        cairo-based gtk+-2.0 theme engine
ii  gtk2-engines-pixbuf:amd64  2.24.33-2ubuntu2   amd64        pixbuf-based theme for GTK 2

**Comment by Phillipus** [comment] 2024-06-25 22:24
I installed a fresh install of Linux Mint Cinnamon 21.3 in a VM and all `gif` images are showing OK.

@nitind Maybe you could check you have the latest updates for Mint, or check if there is something different about your installation, or even, if possible, try a fresh install on another machine or VM?

**Comment by igornem1** [comment] 2024-06-25 23:51
Hi guys, sorry for your effort I pushed you to do, just want add that before I installed Cinnamon it was installed with Mate version and the Cinnamon was installed upon it. The installation process was promised it will erase the previous and install a fresh Cinnamon but probably something went wrong.

**Comment by nitind** [comment] 2024-06-26 00:19
> I installed a fresh install of Linux Mint Cinnamon 21.3 in a VM and all `gif` images are showing OK.
> 
> @nitind Maybe you could check you have the latest updates for Mint, or check if there is something different about your installation, or even, if possible, try a fresh install on another machine or VM?

Unfortunately I tend to only run Fedora. My interest in this problem is as the product owner of the JEE package, and the maintainer of that org.eclipse.jst.servlet.ui plug-in.

**Comment by jonahgraham** [comment] 2024-06-26 01:35
@igornem1 - you have answered which version of g**t**k as opposed to g**d**k. IIUC the problem is libgdk-pixbuf2.0 version, e.g. on my Xubuntu I see 2.42.8. The problematic version *may* be >= 2.42.11

```
$ dpkg -l *pixbuf*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                           Version                Architecture Description
+++-==============================-======================-============-================================================
ii  gir1.2-gdkpixbuf-2.0:amd64     2.42.8+dfsg-1ubuntu0.3 amd64        GDK Pixbuf library - GObject-Introspection
ii  gtk2-engines-pixbuf:amd64      2.24.33-2ubuntu2       amd64        pixbuf-based theme for GTK 2
ii  libgdk-pixbuf-2.0-0:amd64      2.42.8+dfsg-1ubuntu0.3 amd64        GDK Pixbuf library
ii  libgdk-pixbuf-xlib-2.0-0:amd64 2.40.2-2build4         amd64        GDK Pixbuf library (deprecated Xlib integration)
ii  libgdk-pixbuf2.0-0:amd64       2.40.2-2build4         amd64        GDK Pixbuf library (transitional package)
ii  libgdk-pixbuf2.0-bin           2.42.8+dfsg-1ubuntu0.3 amd64        GDK Pixbuf library (thumbnailer)
ii  libgdk-pixbuf2.0-common        2.42.8+dfsg-1ubuntu0.3 all          GDK Pixbuf library - data files
un  libgdk-pixbuf2.0-dev           <none>                 <none>       (no description available)
ii  ruby-gdk-pixbuf2               3.4.3-1+ubuntu5        all          Gdk-Pixbuf 2 bindings for the Ruby language

```

**Comment by akurtakov** [comment] 2024-06-26 05:14
My Fedora 40 still has gdk-pixbuf2-2.42.10-8.fc40.x86_64 so no breakage for me (still?). Even version wouldn't matter that much as whether these codecs are available seems to be controlled by a compile time flag as per https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/169#note_2092832 aka same version might be fine on one distro and not on another.

**Comment by igornem1** [comment] 2024-06-26 06:19
@jonahgraham 
$ dpkg -l *pixbuf*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version                Architecture Description
+++-==========================-======================-============-==================================================================
ii  gir1.2-gdkpixbuf-2.0:amd64 2.42.8+dfsg-1ubuntu0.3 amd64        GDK Pixbuf library - GObject-Introspection
ii  gtk2-engines-pixbuf:amd64  2.24.33-2ubuntu2       amd64        pixbuf-based theme for GTK 2
ii  heif-gdk-pixbuf:amd64      1.14.2-1ubuntu1        amd64        ISO/IEC 23008-12:2017 HEIF file format decoder - gdk-pixbuf loader
ii  libgdk-pixbuf-2.0-0:amd64  2.42.8+dfsg-1ubuntu0.3 amd64        GDK Pixbuf library
un  libgdk-pixbuf2.0-0         <none>                 <none>       (no description available)
ii  libgdk-pixbuf2.0-bin       2.42.8+dfsg-1ubuntu0.3 amd64        GDK Pixbuf library (thumbnailer)
ii  libgdk-pixbuf2.0-common    2.42.8+dfsg-1ubuntu0.3 all          GDK Pixbuf library - data files
un  libgdk-pixbuf2.0-dev       <none>                 <none>       (no description available)
ii  webp-pixbuf-loader         0.0.5-5                amd64        WebP Image format GdkPixbuf loader

**Comment by Phillipus** [comment] 2024-06-26 08:22
> > @nitind Maybe you could check you have the latest updates for Mint, or check if there is something different about your installation, or even, if possible, try a fresh install on another machine or VM?
> 
> Unfortunately I tend to only run Fedora. My interest in this problem is as the product owner of the JEE package, and the maintainer of that org.eclipse.jst.servlet.ui plug-in.

@nitind Sorry, I mistyped. That comment was meant for @igornem1 !

**Comment by igornem1** [comment] 2024-06-26 10:53
Hi @Phillipus ,
I've just removed manually my Linux Mint installation and installed it from beginning and now everything working as expected.
One difference it that I've installed it with distribution package which I've downloaded about 2 monthes ago instead aforementioned one which I've downloaded a day before yesterday. As per checksum files they are identical although has a bit different folder structures, I hope later will have time to check it more thoroughly.
Once again my apologies for a mess, seems the topic can be closed

**Comment by Phillipus** [comment] 2024-06-26 11:04
Clearly this is not just an Eclipse issue but a potential problem for many Linux users/developers that use `gif/bmp/ico/xpm` format images in their tools. I guess it depends on the distro. I'm still unclear if the issue will be reverted:

https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/846

**Comment by jonahgraham** [comment] 2024-06-26 12:33
@igornem1 I am glad to hear that a fresh install worked. I can't tell enough from the versions of pixbuf you have if that is the reason it failed (it seems unlikely someone built 2.42.8+dfsg-1ubuntu0.3 differently - without gif codec - for Ubuntu than Mint). There could be some other failure unrelated to the pixbuf included codecs change, but especially now that you have a working system I don't know how to diagnose this further.

Regardless, you have brought this to our collective attention, but it looks like Eclipse is going to rely on the Distros to keep including gif support as pixbuf goes through its refactoring.

I don't think there is any additional action here for now, but eventually Eclipse may have to replace all gifs with png, or add a different library to load gif files. The former would be a bug report on every single project, the latter would be an SWT change.

I have created the SWT issue https://github.com/eclipse-platform/eclipse.platform.swt/issues/1307 and I am going to close this issue. AFAICT there is nothing that Eclipse Packaging Project can do here.

**Closed by jonahgraham** 2024-06-26 12:33 UTC

**Comment by iloveeclipse** [comment] 2024-06-26 12:45
What I can't understand: was it a "mistake" in Gnome or not, as the issue https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/846 is not closed / fixed? 

Do we have a pointer to a Gnome ticket that would say "let remove gif/bmp/ico" support in XYZ version?

**Comment by jonahgraham** [comment] 2024-06-26 12:55
IIUC it was disabled in Gnome by mistake, but it was disabled in the underlying library (gdk-pixbuf) on [purpose](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/163#note_2070624). The challenge is that consumers of gdk-pixbuf needed to make a build script change between 2.42.10 and 2.42.11 (add `-Dothers=enabled` to compiler flags of gdk-pixbuf). It was documented in gdk-pixbuf [NEWS](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/blob/5a5d37bd6696c96d5567c2199cac0fbc5b86d0e8/NEWS#L14) - but you would have to know that gif (and others) were considered fringe by the gdk-pixbuf maintainers.

**Comment by iloveeclipse** [comment] 2024-06-26 13:02
Sometimes I wonder if GTK developers are actually using what they produce.
A world without gif isn't imaginable, how would we survive without all that?
![hell_yeah](https://github.com/eclipse-packaging/packages/assets/964108/19b6a3da-235c-4a14-918f-6063c1db1507)
